## Descargamos una versión concreta de httpd:2.4
FROM httpd:2.4
## Creamos un fichero index.html en el directorio por defecto de nginx
RUN echo "Mi primer Dockerfile. Hola Mundo!" > /usr/local/apache2/htdocs/index.html
## Exponemos el Puerto 80
EXPOSE 80